<?php
namespace Src\Submission\Domain\Submission;

interface SubmissionArtifactRepository
{
    /** $id is generated by the caller up front, so it can also appear in submission_packages.layer2_artifact_ids. */
    public function create(string $id, string $submissionId, string $filename, ArtifactType $type, string $storagePath): void;

    /** @return SubmissionArtifactDetail[] */
    public function findAllForSubmission(string $submissionId): array;
}
